version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    hostname: keycloak
    environment:
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: ${POSTGRES_URL}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - ./realms/realm.json:/opt/keycloak/data/import/demo-realm.json:ro
    networks:
      - public
      - private

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - private

  keycloak-integration:
    container_name: keycloak-integration
    image: keycloak-integration:latest
    ports:
      - "8081:8080"
    depends_on:
      - keycloak
    networks:
      - private
      - public

volumes:
  postgres-data:

networks:
  public:
    driver: bridge

  private:
    driver: bridge
    internal: true