server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/myrealm
        registration:
          keycloak:
            client-id: gateway-client
            client-secret: mysecret
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/myrealm